theme: jekyll-theme-cayman
title: A C&Ollection of Python useful tutorials 
description: This website provides a collection of Python tutorials that cover a wide variety of topics, ranging from linear optimziation, to statistics, machine learning etc. 
